name: test

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build test
        run: |
          cc  -o test test/global_test.c
      - name: Run test
        run: ./test

  ubuntu:
    strategy:
      matrix:
        cc: [gcc, clang]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Build test
        run: |
          ${{ matrix.cc }} -o test test/global_test.c 
      - name: Run test
        run: ./test
      
